(.venv_eggroll) app@ubuntu:~/workspace/Eggroll_deploy/python/eggroll/roll_pair/test$ python -m unittest test_roll_pair.TestRollPairCluster
static conf path: /home/app/workspace/Eggroll_deploy/conf/eggroll.properties
er_session_py_20220808.183523.631_192.168.222.133
10
aggregate result:  25
....[(4, [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])]
..before delete:[('k3', 'v3'), ('k2', 'v2'), ('k4', 'v4'), ('k1', 'v1')]
after delete:[('k3', 'v3'), ('k2', 'v2'), ('k4', 'v4')]
.before destroy:[('k3', 'v3'), ('k2', 'v2'), ('k4', 'v4'), ('k1', 'v1')]
...2
[(b'k1', b'v1'), (b'k2', b'v2')]
.[(1, 1), (3, 3)]
.0
(0, 0)
.[(37001, 37002), (91388, 91389), (11059, 11060), (11060, 11061), (37002, 37003), (45500, 45501), (11058, 11059), (36999, 37000), (37000, 37001), (45499, 45500)]
get value:37002 of key:37001
..[(4, [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])]
.[('a', 3), ('d', 7)]
.left:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3), ('g', 12), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)], right:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)]
111 [('a', 3), ('d', 7), ('f', 3), ('g', 13)]
222 [('a', 3), ('d', 7), ('f', 3), ('g', 13)]
left:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)], right:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3), ('g', 12), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
333 [('a', 3), ('d', 7), ('f', 3), ('g', 13)]
.[('a', 2), ('b', 8)]
.111
222
6
333
..[('0_1', '0'), ('1_1', '1'), ('2_1', '2'), ('3_1', '3'), ('4_1', '4'), ('5_1', '5'), ('6_1', '6'), ('7_1', '7'), ('8_1', '8'), ('9_1', '9')]
..res:[('A_0', 13), ('A_1', 16), ('B_0', 29), ('B_1', 32), ('C_0', 43), ('C_1', 46), ('j_0', 66), ('j_1', 67)]
.[(0, '0map_values'), (1, '1map_values'), (2, '2map_values'), (3, '3map_values'), (4, '4map_values'), (5, '5map_values'), (6, '6map_values'), (7, '7map_values'), (8, '8map_values'), (9, '9map_values')]
..<RollPair(_store=<ErStore(store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=er_session_py_20220808.183523.631_192.168.222.133, name=dc4f5514-1705-11ed-8ce1-000c29f210aa, path=, total_partitions=10, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fb3618cd390>, partitions=[***, len=10], options=[{'total_partitions': '10', 'store_type': 'IN_MEMORY', 'create_if_missing': 'True', 'eggroll.session.processors.per.node': '3', 'include_key ': 'False', 'include_key': 'False', 'eggroll.session.id': 'er_session_py_20220808.183523.631_192.168.222.133'}]) at 0x7fb3618cd9b0>) at 0x7fb3618ccf60>
[(1, '1'), (5, '5'), (2, '2'), (7, '7'), (0, '0'), (4, '4'), (8, '8'), (6, '6'), (9, '9'), (3, '3')]
..<RollPair(_store=<ErStore(store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=er_session_py_20220808.183523.631_192.168.222.133, name=dd3b6f26-1705-11ed-8ce1-000c29f210aa, path=, total_partitions=10, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fb3623b3ba8>, partitions=[***, len=10], options=[{'total_partitions': '10', 'store_type': 'IN_MEMORY', 'create_if_missing': 'True', 'eggroll.session.processors.per.node': '3', 'include_key ': 'False', 'include_key': 'False', 'eggroll.session.id': 'er_session_py_20220808.183523.631_192.168.222.133'}]) at 0x7fb3618d29e8>) at 0x7fb3618dcef0>
[(1, '1'), (5, '5'), (2, '2'), (7, '7'), (0, '0'), (4, '4'), (8, '8'), (6, '6'), (9, '9'), (3, '3')]
....length: 2038
.all:  [(1, 1), (5, 5), (2, 2), (4, 4), (6, 6), (3, 3)]
count:  6
reduce result: 21
.[[ 0  0  0  0  0  0  0  0  0  0 15]]
.....left:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3)], right:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)]
111 [('b', 4), ('e', 0)]
222 10
.[(b'a', b'b')]
1
.E[(5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]
.left:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)], right:[('a', 1), ('b', 4), ('d', 6), ('e', 0)]
111 [('c', 4), ('f', 0), ('g', 1)]
.left:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3), ('g', 12), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)], right:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)]
111 [('b', 4), ('e', 0), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
222 [('c', 4)]
rs: [('b', 4), ('e', 0), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
left:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)], right:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3), ('g', 12), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
333 [('c', 4)]
.get_all:[('something0', 6), ('something10', 3), ('something1', 1), ('something2', 2), ('something3', 2), ('something4', 6), ('something5', 5), ('something16', 6), ('something125', 4)]
start take
['something0', 'something10', 'something1', 'something2', 'something3', 'something4']
get_all:[('something0', 6), ('something10', 3), ('something1', 1), ('something2', 2), ('something3', 2), ('something4', 6), ('something5', 5), ('something16', 6), ('something125', 4)]
start take
[('something0', 6), ('something10', 3), ('something1', 1), ('something2', 2), ('something3', 2), ('something4', 6)]
get_all:[('something1.25', 4), ('something1.34', 3), ('something0.105', 6), ('something1', 1), ('something2', 2), ('something3', 2), ('something1.0', 3), ('something0.104', 6), ('something1.105', 5)]
start take
['something1.25', 'something1.34', 'something0.105', 'something1', 'something2', 'something3']
get_all:[('something1.25', 4), ('something1.34', 3), ('something0.105', 6), ('something1', 1), ('something2', 2), ('something3', 2), ('something1.0', 3), ('something0.104', 6), ('something1.105', 5)]
start take
[('something1.25', 4), ('something1.34', 3), ('something0.105', 6), ('something1', 1), ('something2', 2), ('something3', 2)]
get_all:[('1', '1'), ('4', '4'), ('9', '9'), ('18', '8'), ('23', '3'), ('0', '0'), ('6', '6'), ('7', '7'), ('35', '5'), ('1112', '2')]
start take
['1', '4', '9', '18', '23', '0']
get_all:[('1', '1'), ('4', '4'), ('9', '9'), ('18', '8'), ('23', '3'), ('0', '0'), ('6', '6'), ('7', '7'), ('35', '5'), ('1112', '2')]
start take
[('1', '1'), ('4', '4'), ('9', '9'), ('18', '8'), ('23', '3'), ('0', '0')]
get_all:[('1', '1'), ('4', '4'), ('1112.1', '2'), ('18.2', '9'), ('18.3', '8'), ('23.9', '3'), ('35.2', '5'), ('0', '0'), ('23.6', '7'), ('35.1', '6')]
start take
['1', '4', '1112.1', '18.2', '18.3', '23.9']
get_all:[('1', '1'), ('4', '4'), ('1112.1', '2'), ('18.2', '9'), ('18.3', '8'), ('23.9', '3'), ('35.2', '5'), ('0', '0'), ('23.6', '7'), ('35.1', '6')]
start take
[('1', '1'), ('4', '4'), ('1112.1', '2'), ('18.2', '9'), ('18.3', '8'), ('23.9', '3')]
get_all:[('3something', 2), ('3tomething', 2), ('1.34something', 3), ('0.105something', 6), ('1.105something', 5), ('1something', 1), ('2something', 2), ('1.0something', 3), ('1.25something', 4)]
start take
['3something', '3tomething', '1.34something', '0.105something', '1.105something', '1something']
get_all:[('3something', 2), ('3tomething', 2), ('1.34something', 3), ('0.105something', 6), ('1.105something', 5), ('1something', 1), ('2something', 2), ('1.0something', 3), ('1.25something', 4)]
start take
[('3something', 2), ('3tomething', 2), ('1.34something', 3), ('0.105something', 6), ('1.105something', 5), ('1something', 1)]
.<RollPair(_store=<ErStore(store_locator=<ErStoreLocator(id=0, store_type=LMDB, namespace=testUnionLeft2020, name=ns1202010, path=, total_partitions=1, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fb360584400>, partitions=[***, len=1], options=[{'eggroll.session.processors.per.node': '3', 'create_if_missing': 'True', 'include_key': 'False', 'eggroll.session.id': 'er_session_py_20220808.183523.631_192.168.222.133'}]) at 0x7fb360584c88>) at 0x7fb36045e400>
<RollPair(_store=<ErStore(store_locator=<ErStoreLocator(id=0, store_type=LMDB, namespace=testUnionRight2020, name=ns12020101, path=, total_partitions=1, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fb36185ea58>, partitions=[***, len=1], options=[{'include_key': 'True', 'eggroll.session.id': 'er_session_py_20220808.183523.631_192.168.222.133', 'total_partitions': '1', 'eggroll.session.processors.per.node': '3', 'create_if_missing': 'True'}]) at 0x7fb3605847b8>) at 0x7fb360611550>
[(0, 1), (1, 3), (2, 5), (3, 3)]
left: <RollPair(_store=<ErStore(store_locator=<ErStoreLocator(id=0, store_type=LMDB, namespace=testUnionLeft2020, name=namespace20200110, path=, total_partitions=1, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fb360584cc0>, partitions=[***, len=1], options=[{'total_partitions': '1', 'eggroll.session.processors.per.node': '3', 'create_if_missing': 'True', 'include_key': 'False', 'eggroll.session.id': 'er_session_py_20220808.183523.631_192.168.222.133'}]) at 0x7fb3605849b0>) at 0x7fb36041b128>
right: <RollPair(_store=<ErStore(store_locator=<ErStoreLocator(id=0, store_type=LMDB, namespace=testUnionRight2020, name=namespace20200110, path=, total_partitions=1, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fb360611358>, partitions=[***, len=1], options=[{'create_if_missing': 'True', 'include_key': 'True', 'eggroll.session.id': 'er_session_py_20220808.183523.631_192.168.222.133', 'total_partitions': '1', 'eggroll.session.processors.per.node': '3'}]) at 0x7fb3619434e0>) at 0x7fb361935208>
left: [(0, 1), (1, 2), (2, 3)]
right: [(1, 1), (2, 2), (3, 3)]
[(0, 1), (1, 3), (2, 5), (3, 3)]
.left:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3), ('g', 12), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)], right:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)]
111 [('a', 3), ('b', 4), ('c', 4), ('d', 7), ('e', 0), ('f', 3), ('g', 13), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
222 [('a', 3), ('b', 4), ('c', 4), ('d', 7), ('e', 0), ('f', 3), ('g', 13), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
left:[('a', 2), ('c', 4), ('d', 1), ('f', 0), ('g', 1)], right:[('a', 1), ('b', 4), ('d', 6), ('e', 0), ('f', 3), ('g', 12), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
333 [('a', 3), ('b', 4), ('c', 4), ('d', 7), ('e', 0), ('f', 3), ('g', 13), ('h', 13), ('i', 14), ('j', 15), ('k', 16), ('l', 17)]
.
======================================================================
ERROR: test_session_meta (test_roll_pair.TestRollPairCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/client.py", line 84, in sync_send
    response = _command_stub.call(request.to_proto())
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application:

==== detail start, at 20220808.183554.441 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_service.py", line 33, in call
    kwargs=getattr(command_request, '_kwargs'))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 94, in dispatch
    raise e
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError:

==== detail start, at 20220808.183554.437 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====



==== detail end ====

"
        debug_error_string = "{"created":"@1659954954.442741538","description":"Error received from peer ipv4:192.168.222.133:34137","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Exception calling application: \n\n==== detail start, at 20220808.183554.441 ====\nTraceback (most recent call last):\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task\n    value=self.functor_serdes.serialize(f(task)))\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs\n    eggs = input_adapter.get('eggs')\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get\n    return self.data[key]\nKeyError: 'eggs'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_service.py", line 33, in call\n    kwargs=getattr(command_request, '_kwargs'))\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 94, in dispatch\n    raise e\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 91, in dispatch\n    call_result = _method(_instance, *deserialized_args)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 194, in wrapper\n    raise RuntimeError(msg)\nRuntimeError: \n\n==== detail start, at 20220808.183554.437 ====\nTraceback (most recent call last):\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task\n    value=self.functor_serdes.serialize(f(task)))\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs\n    eggs = input_adapter.get('eggs')\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get\n    return self.data[key]\nKeyError: 'eggs'\n\n==== detail end ====\n\n\n\n==== detail end ====\n\n","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 83, in test_session_meta
    print(table.with_stores(get_eggs))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/aspects.py", line 30, in wrapper
    result = func(*args, **kwargs)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/roll_pair.py", line 1152, in with_stores
    ret_pair = future.result()[0]
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/datastructure/threadpool.py", line 51, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/client.py", line 97, in sync_send
    raise CommandCallError(command_uri, endpoint, e)
eggroll.core.client.CommandCallError: ('Failed to call command: CommandURI(_uri=v1/egg-pair/runTask) to endpoint: 192.168.222.133:34137, caused by: ', <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application:

==== detail start, at 20220808.183554.441 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_service.py", line 33, in call
    kwargs=getattr(command_request, '_kwargs'))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 94, in dispatch
    raise e
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError:

==== detail start, at 20220808.183554.437 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====



==== detail end ====

"
        debug_error_string = "{"created":"@1659954954.442741538","description":"Error received from peer ipv4:192.168.222.133:34137","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Exception calling application: \n\n==== detail start, at 20220808.183554.441 ====\nTraceback (most recent call last):\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task\n    value=self.functor_serdes.serialize(f(task)))\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs\n    eggs = input_adapter.get('eggs')\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get\n    return self.data[key]\nKeyError: 'eggs'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_service.py", line 33, in call\n    kwargs=getattr(command_request, '_kwargs'))\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 94, in dispatch\n    raise e\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 91, in dispatch\n    call_result = _method(_instance, *deserialized_args)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 194, in wrapper\n    raise RuntimeError(msg)\nRuntimeError: \n\n==== detail start, at 20220808.183554.437 ====\nTraceback (most recent call last):\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task\n    value=self.functor_serdes.serialize(f(task)))\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs\n    eggs = input_adapter.get('eggs')\n  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get\n    return self.data[key]\nKeyError: 'eggs'\n\n==== detail end ====\n\n\n\n==== detail end ====\n\n","grpc_status":2}"
>)

----------------------------------------------------------------------
Ran 48 tests in 48.676s

FAILED (errors=1)
(.venv_eggroll) app@ubuntu:~/workspace/Eggroll_deploy/python/eggroll/roll_pair/test$